// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz_EmEHMBlmLeFwuOzaiAG_iOQlGAN7jo',
    appId: '1:394046565827:web:f29b6ca326af943c782176',
    messagingSenderId: '394046565827',
    projectId: 'todoappfire-b56c5',
    authDomain: 'todoappfire-b56c5.firebaseapp.com',
    storageBucket: 'todoappfire-b56c5.appspot.com',
    measurementId: 'G-D1DXD8TEC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPATdMO7KajgYCPlTSNtLbtPIsM2IaB60',
    appId: '1:394046565827:android:6a8f98cc26ce25ab782176',
    messagingSenderId: '394046565827',
    projectId: 'todoappfire-b56c5',
    storageBucket: 'todoappfire-b56c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8NW4e4w0_2W9Hjmh6RFYGZuuETLPJbW4',
    appId: '1:394046565827:ios:4cbb657650852b6b782176',
    messagingSenderId: '394046565827',
    projectId: 'todoappfire-b56c5',
    storageBucket: 'todoappfire-b56c5.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8NW4e4w0_2W9Hjmh6RFYGZuuETLPJbW4',
    appId: '1:394046565827:ios:27405c51ee81b3ec782176',
    messagingSenderId: '394046565827',
    projectId: 'todoappfire-b56c5',
    storageBucket: 'todoappfire-b56c5.appspot.com',
    iosBundleId: 'com.example.toDoList.RunnerTests',
  );
}
